---
gateway:
  admin:
    enabled: false
    http:
      enabled: false

  env:
    # log_level: debug
    plugins: bundled #,rate-limiting
  # customEnv:
  #   MY_ADDITIONAL_ENV: '1234'
  image:
    pullPolicy: IfNotPresent # Never # Always
    # pullSecrets:
    # - TLS_SECRET_NAME
    repository: kong
    tag: 3.9.0
  # ingress:
  #   enabled: true
  #   ingressClassName: external
  proxy:
    annotations: {}
    enabled: true
    # externalTrafficPolicy: Local
    http:
      enabled: true
      servicePort: 0
      containerPort: 8000
      parameters: []
    # loadBalancerIP: 192.168.54.155
    tls:
      enabled: true
      servicePort: 0
      containerPort: 8443
      parameters:
      - http2
    type: LoadBalancer
